version: "3.2"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: khoibv/docker-starter:part2
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - target: 80
        published: 8088
        #protocol: tcp
        # disable routing mesh https://docs.docker.com/engine/swarm/ingress/#publish-a-port-for-a-service
        mode: host
        
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    #volumes:
    #  - "./redis/data:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet: